apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "legalassist-ai.fullname" . }}
  labels:
    {{- include "legalassist-ai.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "legalassist-ai.selectorLabels" . | nindent 6 }}
